services:
  auth:
    build:
      context: ./apps/auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/auth:/app
    environment:
      - GIN_MODE=debug

  core:
    build:
      context: ./apps/core
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/core:/app
    environment:
      - GIN_MODE=debug

  front:
    build:
      context: ./apps/front
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/front:/app
      - /app/node_modules
